public class Nurse{
    private String name;
    private int id;
    private String department;
    private String position;

    public nurse(String name, int id, String department, String position){
        this.name = name;
        this.id = id;
        this.department = department;
        this.position = position;
    }
    public String getName(){
        return name;
    }
    public int getId(){
        return id;
    }
    public String getDepartment(){
        return department;
    }
    public String getPosition(){
        return position;
    }
    //hello test test
    hello hello
}
